In [2]:
import torch
import torch.nn.functional as F
from torch import nn

In [4]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super(CenteredLayer, self).__init__()
    
    def forward(self, X):
        return X - X.mean()

In [5]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [7]:
net = nn.Sequential(
    nn.Linear(8, 128),
    CenteredLayer()
)

In [8]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(6.0536e-09, grad_fn=<MeanBackward0>)

In [9]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super(MyLinear, self).__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return linear

In [10]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.6814,  0.8165, -1.8272],
        [-1.5660, -0.1807,  0.0080],
        [ 1.1500, -0.2627,  0.2543],
        [-0.9831, -0.2822, -0.4829],
        [-0.3380, -0.5385, -0.7109]], requires_grad=True)

In [11]:
linear(torch.rand(2, 5))

tensor([[-0.8498,  1.9446, -1.9918],
        [-1.2270,  2.1290, -1.4444]])

In [12]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[  4.1826],
        [-17.0938]])